### ISSUE TITLE
Allow dynamically getting permissions from MySQL, aka disable permission caching

### ISSUE THREAD

**Issue by rautamiekka** [Avankziar/BungeeTeleportManager#3]
Currently the plugin has only 1 option for how permissions are gotten from the database: get them all, cache, and never re-check for changes, which means changing a permission in MySQL requires a full reboot of all applicable 'Minecraft' Servers. I suspect that changing a permission in a non-MySQL LuckPerms would pose the same problem, but I haven't tested.

Please add a config option to disable caching of permissions, to instead dynamically get the permissions when a permission check is needed:
1. ask MySQL for the applicable permissions
2. do stuff
3. forget the permission.

**Comment by Avankziar** [comment]
I must admit, I have never dealt with this before, but I will.

**Comment by Avankziar** [comment]
I have now looked into the subject. Let's take LuckPerms as an example PermissionSystem.
This plugin does all the permission actuality. Accordingly, if this is set correctly(in Luckperms), the permission should always be compared directly with the source (database, etc.).
So in BTM I don't have to change anything like that, because it is PermissionSystem specific anyway.

If you didn't mean this example, I would need more input for your example. Because on my test server and external server, such a problem has not occurred yet. At least as far as I understood your example.

Avan
